#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --job-name=01.ion_norm.ID
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem=48G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jjung658@usc.edu
#SBATCH --output=01.ion_norm.ID_JJ.out

#wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
#gzip -d GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

pathVCF=/home1/jjung658/scratch2/newcovid19/ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_recal.vcf.gz
pathRef=/home1/jjung658/scratch2/newcovid19/ref_dat/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
tmp_pathOut=tmp_ion.normID.noChrM.vqsr.flt.vcf.gz
pathOut=ion.normID.noChrM.vqsr.flt.vcf.gz

bcftools stats ${pathVCF} | head

echo "####################################"
date
echo "Normalizing and left aligns / chr filtering"
bcftools stats ${pathVCF} | head
echo "####################################"

bcftools filter -r chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX \
  "${pathVCF}" -Ou | \
  bcftools norm -m -any --check-ref w -f "${pathRef}" -Ou | \
  bcftools annotate --set-id '%CHROM:%POS:%REF:%FIRST_ALT' -Oz > "${tmp_pathOut}"
bcftools index -t "${tmp_pathOut}"


echo "####################################"
date
echo "PASS filtering"
bcftools stats ${tmp_pathOut} | head
echo "####################################"
bcftools view --threads 8 -f PASS ${tmp_pathOut} -Oz -o ${pathOut}
bcftools index -t ${pathOut}
bcftools stats ${pathOut} | head
