#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --job-name=VariantRecalibrator
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=60G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jjung658@usc.edu
#SBATCH --output=7.ion_VariantRecalibrator_gatk4_newcovid19.out

module purge
module load gcc/8.3.0
module load openblas/0.3.8
module load r/4.1.0
module load intel
module load jdk

echo "####################################"
date
echo "VariantRecalibrator"
echo "####################################"

mkdir -p /home1/jjung658/scratch2/tmp/$SLURM_JOBID

tools_newcovid19/gatk-4.2.0.0/gatk --java-options "-Djava.io.tmpdir=/home1/jjung658/scratch2/tmp/$SLURM_JOBID -Xms58G -Xmx58G -XX:ParallelGCThreads=1" VariantRecalibrator \
  -V ion_res_gatk4_newcovid19/ion_gatk4_newcovid19.vcf.gz \
  -O ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.recal \
  --tranches-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.tranches \
  --rscript-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.plots.R \
  --output-model ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.modle \
  --trust-all-polymorphic \
  -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 \
  -an QD -an MQ -an MQRankSum -an ReadPosRankSum -an FS -an SOR -an DP \
  -mode SNP \
  --max-gaussians 6 \
  --use-allele-specific-annotations \
  --resource:hapmap,known=false,training=true,truth=true,prior=15 ref_dat/ref_gatk_newcovid19/hapmap_3.3.hg38.vcf.gz \
  --resource:omni,known=false,training=true,truth=true,prior=12 ref_dat/ref_gatk_newcovid19/1000G_omni2.5.hg38.vcf.gz \
  --resource:1000G,known=false,training=true,truth=false,prior=10 ref_dat/ref_gatk_newcovid19/1000G_phase1.snps.high_confidence.hg38.vcf.gz \
  --resource:dbsnp,known=true,training=false,truth=false,prior=7 ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.dbsnp138.vcf


tools_newcovid19/gatk-4.2.0.0/gatk --java-options "-Djava.io.tmpdir=/home1/jjung658/scratch2/tmp/$SLURM_JOBID -Xms58G -Xmx58G -XX:ParallelGCThreads=1" VariantRecalibrator \
  -V ion_res_gatk4_newcovid19/ion_gatk4_newcovid19.vcf.gz \
  -O ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.recal \
  --tranches-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.tranches \
  --rscript-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.plots.R \
  --output-model ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.modle \
  --trust-all-polymorphic \
  -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.5 -tranche 99.0 -tranche 97.0 -tranche 96.0 -tranche 95.0 -tranche 94.0 -tranche 93.5 -tranche 93.0 -tranche 92.0 -tranche 91.0 -tranche 90.0 \
  -an FS -an ReadPosRankSum -an MQRankSum -an QD -an SOR -an DP \
  -mode INDEL \
  --max-gaussians 4 \
  --use-allele-specific-annotations \
  --resource:mills,known=false,training=true,truth=true,prior=12 ref_dat/ref_gatk_newcovid19/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
  --resource:axiomPoly,known=false,training=true,truth=false,prior=10 ref_dat/ref_gatk_newcovid19/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz \
  --resource:dbsnp,known=true,training=false,truth=false,prior=2 ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.dbsnp138.vcf

echo "####################################"
date
echo "ApplyVQSR"
echo "####################################"

tools_newcovid19/gatk-4.2.0.0/gatk --java-options "-Djava.io.tmpdir=/home1/jjung658/scratch2/tmp/$SLURM_JOBID -Xms58G -Xmx58G -XX:ParallelGCThreads=1" ApplyVQSR \
  -O ion_res_gatk4_newcovid19/tmp_ion_gatk4_newcovid19_recal_INDEL.vcf.gz \
  -V ion_res_gatk4_newcovid19/ion_gatk4_newcovid19.vcf.gz \
  --recal-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.recal \
  --tranches-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_INDEL.tranches \
  --truth-sensitivity-filter-level 99.7 \
  --create-output-variant-index true \
  -mode INDEL \
  --use-allele-specific-annotations


tools_newcovid19/gatk-4.2.0.0/gatk --java-options "-Djava.io.tmpdir=/home1/jjung658/scratch2/tmp/$SLURM_JOBID -Xms58G -Xmx58G -XX:ParallelGCThreads=1" ApplyVQSR \
  -O ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_recal.vcf.gz \
  -V ion_res_gatk4_newcovid19/tmp_ion_gatk4_newcovid19_recal_INDEL.vcf.gz \
  --recal-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.recal \
  --tranches-file ion_res_gatk4_newcovid19/ion_gatk4_newcovid19_SNP.tranches \
  --truth-sensitivity-filter-level 99.7 \
  --create-output-variant-index true \
  -mode SNP \
  --use-allele-specific-annotations
